# Generated by Django 5.1.5 on 2025-02-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comic',
            name='status',
            field=models.CharField(choices=[('completed', 'Completed'), ('ongoing', 'Ongoing'), ('hiatus', 'Hiatus'), ('dropped', 'Dropped'), ('season end', 'Season End'), ('coming soon', 'Coming Soon')], max_length=15, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='type',
            name='name',
            field=models.CharField(choices=[('manga', 'Manga'), ('manhwa', 'Manhwa'), ('manhua', 'Manhua'), ('comic', 'Comic')], max_length=6, verbose_name='Name'),
        ),
    ]
