import Rightbar from "@/app/components/base/Rightbar";
import Leftbar from "@/app/components/base/Leftbar";

import type { Metadata } from "next";
export default function Index() {
  return (
    <>
      <Leftbar />
      <Rightbar />
    </>
  );
}

export const metadata: Metadata = {
  title: "Rhixe Scans",
  description: "Generated by rhixe Scans",
};
