import "./utils/alpine_init";
import "./utils/hyper_init";
import "./utils/htmx_init";
import "./utils/default_table";
import "./functions/backtotop";
import "./functions/navbar";
import "./functions/searchbar";
import "./functions/myaccordian";
import "./functions/carousel";
