# Generated by Django 5.1.9 on 2025-05-17 21:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("libary", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chapter",
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "Chapter",
                "verbose_name_plural": "Chapters",
            },
        ),
        migrations.AlterModelOptions(
            name="comic",
            options={
                "ordering": ["-updated_at"],
                "verbose_name": "Comic",
                "verbose_name_plural": "Comics",
            },
        ),
    ]
