# Generated by Django 5.2 on 2025-04-11 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("libary", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chapter",
            options={"get_latest_by": "created_at", "ordering": ["-updated_at"]},
        ),
        migrations.AlterModelOptions(
            name="comic",
            options={"get_latest_by": "created_at", "ordering": ["-updated_at"]},
        ),
    ]
